### ISSUE TITLE
Bug in high-z (?) galaxy ellipticity assignments?

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/cosmodc2#10]
Here's the printout from the ellipticity-distribution test. Note there are 0 galaxies passing the morphology cuts disk and late for the last file read in (which I believe is for 2<z<3), They may just all be failing the i<24 cut, but this  should be checked..
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology LRG = 1024762
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology early = 607845
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology disk = 503896
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology late = 295555
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology LRG = 487499
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology early = 93836
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology disk = 18380
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology late = 1580
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology LRG = 1273
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology early = 17
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology disk = 0
Number of cosmoDC2_v0.1_test galaxies passing selection cuts for morphology late = 0

**Comment by dkorytov** [comment]
The ellipticity model seems to be fine at high red shifts. There is a decline in galaxies that pass the i<24 cut in high redshift of course. If someone points me to the selection criteria and make the same cuts to double check that we should have few or no galaxies making it into the sample. 

**Ellipticities for all galaxies (left: ellipticity, center: disk elasticity, right: bulge ellipticity)**
![screenshot from 2018-08-14 17-17-45](https://user-images.githubusercontent.com/25048061/44121959-5d841880-9fe7-11e8-9397-6427f7f70269.png)

**Ellipticities for galaxies i < 24 (left: ellipticity, center: disk elasticity, right: bulge ellipticity)**
![screenshot from 2018-08-14 17-28-24](https://user-images.githubusercontent.com/25048061/44122050-c9668100-9fe7-11e8-82d6-5e7cd8549a3a.png)

**Comment by evevkovacs** [comment]
The selection criteria are listed right on the DESCQA plots and also in the summary file. Basically they are i<24, various choices for B/T and M_V (V-band magnitude)
See for example [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-08-13_4&test=ellipticity_dist_COSMOS)

**Comment by aphearin** [comment]
Based on the above plots, this seems to be simply a relic of the cuts and not a problem with the mock.
