### ISSUE TITLE
Halo_id (target_halo_tag) isn't unique

### ISSUE THREAD

**Issue by dkorytov** [LSSTDESC/cosmodc2#13]
target_halo_tag is repeating (Not just the synthetic low mass galaxies). We need to figure out what's going.

**Comment by aphearin** [comment]
@dkorytov - Shouldn’t this be repeated since there are satellites occupying the same host?

**Comment by evevkovacs** [comment]
Yes, but the halo id's are also repeating across snapshots and healpix files. It was confusing to one of the catalog users at DC2 afternoon who was trying to search on halo id and expecting to find unique entries for all centrals. This is something I need to fix in the um_healpix outputs.
