### ISSUE TITLE
confirm persistence of black hole model quantities

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#16]
During the last DESC meeting, @evevkovacs wanted to confirm with @dkorytov that the empirical black hole model was indeed over-writing the Galacticus values of black hole mass and accretion rate, and also that the modeled eddington ratio correctly persists through the pipeline in a way that users can access via the GCR as a native model quantity. 

Passing this issue for @dkorytov to close once this behavior is confirmed.

**Comment by dkorytov** [comment]
It looks like I'm doing things correctly in the code. Are the BH quantities
acting funny?

-Dan

**Comment by evevkovacs** [comment]
Not to my knowledge, but it has never been checked.

**Comment by dkorytov** [comment]
Alright, I'll make some plots to check.
-Dan

**Comment by aphearin** [comment]
No cause for rush on this, Dan, especially since we have no reason to believe that anything is amiss. Feel free to leave this issue open and come back to it when you aren't pressed for time.

**Comment by aphearin** [comment]
I confirmed this with the following plots made from `cosmoDC2_v0.4`:

![bh_bulge_mass_scaling_cosmodc2_v0 4](https://user-images.githubusercontent.com/6951595/43984908-27fc06a8-9cc9-11e8-8b38-e8b86682faa0.png)
![bh_mass_accretion_rates_cosmodc2_v0 4](https://user-images.githubusercontent.com/6951595/43984909-280fa0d2-9cc9-11e8-8342-be6de21e798b.png)

These are clearly our smooth scaling relations for black hole mass and accretion rate, not the properties in Galacticus, so I think these plots validate the persistence of the black hole quantities through our pipeline.
