### ISSUE TITLE
Discreteness in observed red sequence color vs. redshift

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#18]
Scatter plots of flux observed through SDSS filters show mild discreteness effects as a function of redshift; these effects are magnified for fluxes observed through LSST filters.

@dkorytov is currently looking into this and so tagging him to post a plot of what he finds whenever he's done.

**Comment by dkorytov** [comment]
Here's a plot of the issue:
![Observer Frame Colors for SDSS & LSST filters for Central Galaxies in Clusters](https://user-images.githubusercontent.com/25048061/43600816-483e9a4e-9651-11e8-89b3-39a68fb991d9.png)

**Comment by dkorytov** [comment]
By putting in a SDSS g-r vs g-r LSST difference limit and changing some weights on the KDTree, the discrete jumps in the bright red sequence galaxies in g-r color went away at z~0.6 & z~0.9 (Fig 1. & Fig 2)  There is no interpolation as a function of redshift for this run. For the KDTree weights, I down weighed the requirement to match on r-band by a factor of 3, and rest frame g-r and red sequence observed i-z by a factor 2. It looked like trying to match those colors drove jump onto a different population of galaxies. r-i and i-z colors still look okay as before (Fig 3 for r-i, Fig 4 for i-z).

There maybe new discreteness in red sequence at the fainter end or it could be an artifact from the lack of interpolation (Fig 2). 

On a side note, if we don't magnify the dust effect, the discreteness disappears but we no longer are able to match the model color distribution as well.   

![Base Red Sequence Colors](https://user-images.githubusercontent.com/25048061/43851715-14205d56-9b01-11e8-9738-32c277a01fd3.png)

![g-r red sequence colors](https://user-images.githubusercontent.com/25048061/43852694-7fe342cc-9b03-11e8-922a-ededb60eb0e0.png)

![screenshot from 2018-08-08 12-10-25](https://user-images.githubusercontent.com/25048061/43853193-055a206e-9b05-11e8-9bd6-0fb94acd4d1e.png)

![screenshot from 2018-08-08 12-12-22](https://user-images.githubusercontent.com/25048061/43853209-11da7f0a-9b05-11e8-8d04-74f3a0322f7a.png)

**Comment by dkorytov** [comment]
A strong i-z discreteness effect that's visible in v0.1.0 is now also supressed (Fig 4 v0.3.10, Fig 5 v0.1.0)

**Fig 5 LSST red sequence i-z color in the older v0.1.0 catalog**
![screenshot from 2018-08-08 12-26-55](https://user-images.githubusercontent.com/25048061/43853648-600ac332-9b06-11e8-9f9e-685dcf4001c0.png)

**Comment by dkorytov** [comment]
CosmoDC2 v0.4.0 doesn't have amplified effects of dust like the previous catalogs. Removing the dust amplification removed the discreteness artifacts that were visible in color-redshift distributions of red sequence galaxies. 

***CosmoDC2 v0.4.0 Red Sequence Galaxies in Clusters***
![screenshot from 2018-08-13 11-27-41](https://user-images.githubusercontent.com/25048061/44045078-1a7f8bdc-9eed-11e8-8250-3de8c755bb75.png)
