### ISSUE TITLE
validate discreteness in SEDs

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#20]
To minimize discreteness effects from Monte Carlo resampling, we have been adapting the model to behave smoothly in broadband flux/color vs. redshift, but we have not been verifying the SEDs also behave smoothly, so this should be tested using the same analysis that @dkorytov is already using to validate the broadband flux/color evolution.

**Comment by dkorytov** [comment]
I've looked at all the SEDs as a function of redshift and they all look incredibly smooth.
![SED luminosity vs redshift](https://user-images.githubusercontent.com/25048061/43739084-7aac19f0-998c-11e8-9304-4316a0903105.png)

A couple galaxies (1-10) have zero flux through two SED top hats. These galaxies aren't particularly faint either (Mr ~ -20). Should we raise this as a new issue?

**Comment by aphearin** [comment]
That's great news. If you are able to simply record a list of galaxy IDs that have this weird outlier property then that's great. If not, just raise a very brief Issue and mark it with the post-cosmoDC2 milestone. Either way, let's consider this issue closed.
