### ISSUE TITLE
validate evolution of color-color space

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#25]
This is related to #20, but comparing restframe and observed color-color diagrams as a function of redshift.

**Comment by dkorytov** [comment]
No trace of discrete time steps:
![not a single trace](https://user-images.githubusercontent.com/25048061/43745138-d9d272b0-99a2-11e8-91a1-c3e6300b98f4.png)

**Comment by aphearin** [comment]
Looks good. What version of your matchup calculation? The one with finer spacing in dust factors?

**Comment by dkorytov** [comment]
This is CosmoDC2 v0.1.0, there are 10 substeps and x1, x3, x6 dust.
