### ISSUE TITLE
Admin privileges for cosmoDC2 repo

### ISSUE THREAD

**Issue by aphearin** [LSSTDESC/cosmodc2#3]
@drphilmarshall - this new LSST-DESC repo has been migrated from one on my public github page. This is the repo storing the source code for all the modeling associated with the extragalactic catalog. Could you please restore my admin privileges to this repo? 

CC @yymao @evevkovacs @dkorytov

**Comment by drphilmarshall** [comment]
Apologies for the delay, @aphearin ! I made an @LSSTDESC/cosmodc2-admins team with you in it, and gave that team Admin access to this repo. Then I made an @LSSTDESC/cosmodc2-developers team containing you, @dkorytov , @evevkovacs , @yymao and @katrinheitmann (based on the existing collaborators list plus your cc list above), and gave that team Write access to this repo. You are the Maintainer of that team, so should be able to add more people as you need to. Thanks Andrew!

**Comment by aphearin** [comment]
Thanks @drphilmarshall!
