### ISSUE TITLE
totalStarFormationRate units

### ISSUE THREAD

**Issue by AlexGKim** [LSSTDESC/cosmodc2#67]
Hi, I would like to confirm the units of the cosmoDC2_v1.0 catalog's native quantity totalStarFormationRate.  In a previous discussion it was stated that it was it was 10 M_star/yr.  The numbers I see are 1 to 1e10, which seems to high for these units.

**Comment by dkorytov** [comment]
I'll double check the units, but I'm pretty sure it's M_star/Gyr.

**Comment by aphearin** [comment]
@AlexGKim - The `galaxyProperties/totalStarFormationRate` column is a native quantity in Galacticus. 
It looks to me like the distribution is in Msun/Gyr, based on the numerical values, but either @abensonca and/or @evevkovacs should confirm exactly what is tabulated.

**Comment by evevkovacs** [comment]
@AlexGKim Note however that there are several native quantities related to star-formation rate: ['totalStarFormationRate', 'baseDC2/sfr_percentile', 'baseDC2/obs_sfr_percentile', 'baseDC2/sfr', 'diskStarFormationRate', 'baseDC2/obs_sfr', 'spheroidStarFormationRate']. The "baseDC2/*" come from the baseline empirical model that is used to predict the rest-frame magnitudes and colors. These are matched to the corresponding Galacticus quantities to select galaxies  from the Galacticus library. The properties of these selected galaxies are used to fill out the properties of each baseline-model galaxy.  We have not checked how well the Galacticus totalStarFormationRate matches the baseDC2/sfr.

**Comment by AlexGKim** [comment]
Thanks for the information!  I should be good.
