### ISSUE TITLE
Provide Snapshot Catalogs for DC2 Analyses

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/cosmodc2#8]
### Snapshot Galaxy Catalogs

Yao has compiled a list of WG requests for all types of snapshot catalogs. Here is that compilation for reference:

<i>Here's a minimal union set of the snapshot data that have been requested by analysis WGs, in the context of DC2. This set is mostly driven by CL, TJP/WL, and LSS. 
- Snapshot catalogs at three redshifts: z = 0.05, 0.2, 0.9 (exact values do not matter; nearby redshifts are OK). Those catalogs should have regular galaxy properties, plus corresponding halo properties: shape, SO mass, concentration (or similar proxies), spin (if possible). 

- Particle snapshots at corresponding redshifts: particles can be downsampled, or calculated as density field (resolution TBD). Tidal field is also needed (already available for protoDC2).

Use cases:

(1) To create IA mocks, the TJP WG will need the tidal field at each galaxy position. Particle snapshots are needed to create the tidal fields, but the TJP WG does not need the snapshots directly for the purpose of creating IA mocks. (Note that the tidal fields are already
available for protoDC2; I list it here to remind us for cosmoDC2.)
(2) For validating IA mocks, snapshot galaxy catalogs and density fields can be useful. This is mostly due to the fact that most programs that computes various 2pt correlations work on snapshots rather than on light cones. Obviously, in the end the analysis WG will have code
that works on light cones, but snapshot data can make the validation process easier.  
(3) For the LSS WG (which I actually haven't heard back and I am guessing their use case here), the snapshot galaxy catalogs would mostly serve as facilitating the validation process. Again this is because it is easier to compute and to interpret the galaxy bias on snapshots. 
(4) The CL WG does require particle snapshots for their science case --- they want to be able to obtain the mass profiles for clusters so that they can validate their mass profile reconstruction. They can use downsampled particle snapshots (for a particle mass ~< 1e12 Msun) and they want z=0.2, 0.5, 0.8. They would need these for cosmoDC2, obviously.</i>

Another use case that was proposed during cosmodc2-fest:
5) TJP need a few galaxy snapshots at low, medium and high z for studying galaxy-bias models.

(Public releases for the snapshot particle data and fof catalogs will happen with the paper that describes them, and are not relevant to this issue.)

We can start to address the above needs by supplying UM mocks with a restricted set of galaxy properties. Need some modifications of the UM pipeline to work on halo-catalog snapshots.

**Comment by evevkovacs** [comment]
This has been completed. Two test snapshot catalogs for the baseDC2 model have been provided  and the fully dresses cosmoDC2 versions with all the galaxy properties will be forthcoming. A reader exists for the baseDC2 snapshots.

**Comment by yymao** [comment]
@evevkovacs should we put the snapshot catalogs (and the corresponding reader) into `GCRCatalogs` so that other people can use them too?

**Comment by evevkovacs** [comment]
yes, i have code ready to go and will submit a PR later today

**Comment by rmandelb** [comment]
Great - are the snapshot catalogs at NERSC?  I wonder if we can find somebody who was going to work with them for their projects who might be willing to write a short tutorial illustrating their use.  Then this could be advertised more widely.  Does that make sense?  Maybe somebody on one of the project teams that wants to use the snapshot catalogs?

**Comment by yymao** [comment]
Agree with @rmandelb. Probably need to wait till the reader is in place though?

**Comment by rmandelb** [comment]
Absolutely, was just thinking ahead :)

**Comment by evevkovacs** [comment]
I have a couple of snapshots made for baseDC2 already. This is the catalog with limited properties. But people could start to look at it. Here's a color distribution validation test for it (https://portal.nersc.gov/project/lsst/descqa/v2/?run=2019-04-23_1&catalog=baseDC2_snapshot_z1.01_v0.1) I just submitted a PR for the reader. Note that this is all for baseDC2 only. We are still working on the cosmoDC2 version with more complete properties.
