### ISSUE TITLE
negative halo IDs

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/cosmodc2#81]
@plaszczy reported in https://github.com/LSSTDESC/DC2-production/issues/305 that there are galaxies in cosmoDC2 v1.0 that have negative `halo_id`.

I can confirm that's the case with the following code. I also see negative `halo_id` in 1.1.4.

```python
import GCRCatalogs
gc = GCRCatalogs.load_catalog('cosmoDC2_v1.0_small')
gc.get_quantities(['halo_id'], ['halo_id < 0'])
```
I don't think this is an "issue" per say, but wonder if this is expected, @dkorytov ?

**Comment by evevkovacs** [comment]
@plaszczy @yymao Yes, it is expected. These negative halo-ids identify the synthetic halos that are added to host the ultra-faint galaxies. The ultra-faint galaxies need to be added to the catalog so that the criteria set by dn/dmag validation tests are satisfied.
